server {
    listen 80;
    server_name localhost;
    root C:\Users\ProBook\PycharmProjects\python_advanced\module_23_cgi_server\homework\hw_2;

    location /static/ {
        alias C:\Users\ProBook\PycharmProjects\python_advanced\module_23_cgi_server\homework\hw_2\static;
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
        try_files $uri =404;
    }

    location / {
        include uwsgi_params;
        uwsgi_pass unix:/tmp/uwsgi.sock;
    }
}